name: "Deploy Lambda Dev"

on:
  workflow_dispatch:
  push:
    branches: [ development ]

env:
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  AWS_REGION: AWS_REGION

jobs:
  deploy:
    name: deploy lambda api wrapper
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy
      run: |
        cp ./config/.env.dev ./.env
        npm install -g serverless
        npm install
        sls deploy --stage dev

